// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(resetn,0,0);
        VL_OUT8(trap,0,0);
        CData/*0:0*/ soc_top__DOT__clk;
        CData/*0:0*/ soc_top__DOT__resetn;
        CData/*0:0*/ soc_top__DOT__trap;
        CData/*0:0*/ soc_top__DOT__mem_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__mem_axi_awready;
        CData/*2:0*/ soc_top__DOT__mem_axi_awprot;
        CData/*0:0*/ soc_top__DOT__mem_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__mem_axi_wready;
        CData/*3:0*/ soc_top__DOT__mem_axi_wstrb;
        CData/*0:0*/ soc_top__DOT__mem_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__mem_axi_bready;
        CData/*1:0*/ soc_top__DOT__mem_axi_bresp;
        CData/*0:0*/ soc_top__DOT__mem_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__mem_axi_arready;
        CData/*2:0*/ soc_top__DOT__mem_axi_arprot;
        CData/*0:0*/ soc_top__DOT__mem_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__mem_axi_rready;
        CData/*1:0*/ soc_top__DOT__mem_axi_rresp;
        CData/*0:0*/ soc_top__DOT__s0_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__s0_axi_awready;
        CData/*0:0*/ soc_top__DOT__s0_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__s0_axi_wready;
        CData/*0:0*/ soc_top__DOT__s0_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__s0_axi_bready;
        CData/*1:0*/ soc_top__DOT__s0_axi_bresp;
        CData/*0:0*/ soc_top__DOT__s0_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__s0_axi_arready;
        CData/*0:0*/ soc_top__DOT__s0_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__s0_axi_rready;
        CData/*1:0*/ soc_top__DOT__s0_axi_rresp;
        CData/*0:0*/ soc_top__DOT__s1_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__s1_axi_awready;
        CData/*0:0*/ soc_top__DOT__s1_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__s1_axi_wready;
        CData/*0:0*/ soc_top__DOT__s1_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__s1_axi_bready;
        CData/*1:0*/ soc_top__DOT__s1_axi_bresp;
        CData/*0:0*/ soc_top__DOT__s1_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__s1_axi_arready;
        CData/*0:0*/ soc_top__DOT__s1_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__s1_axi_rready;
        CData/*1:0*/ soc_top__DOT__s1_axi_rresp;
        CData/*7:0*/ soc_top__DOT__reset_counter;
        CData/*0:0*/ soc_top__DOT__cpu_resetn;
        CData/*0:0*/ soc_top__DOT__w_route_s1;
        CData/*0:0*/ soc_top__DOT__current_w_route;
        CData/*0:0*/ soc_top__DOT__r_route_s1;
        CData/*0:0*/ soc_top__DOT__current_r_route;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__clk;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__resetn;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__trap;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_awready;
        CData/*2:0*/ soc_top__DOT__cpu__DOT__mem_axi_awprot;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_wready;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__mem_axi_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_bready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_arready;
    };
    struct {
        CData/*2:0*/ soc_top__DOT__cpu__DOT__mem_axi_arprot;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_axi_rready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__pcpi_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__pcpi_wr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__pcpi_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__pcpi_ready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__trace_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_valid;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__mem_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_instr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__mem_ready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__clk;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__resetn;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_awready;
        CData/*2:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_awprot;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_wready;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_bready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_arready;
        CData/*2:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_arprot;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_rready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_instr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_ready;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__ack_awvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__ack_arvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__ack_wvalid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__xfer_done;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__clk;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__resetn;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__trap;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_instr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_ready;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_read;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_write;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_wr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_ready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__trace_valid;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_sh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_instr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_ready;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_wstrb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_delay;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_active;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_mul_wr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_mul_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_mul_ready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_div_wr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_div_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_div_ready;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_int_wr;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_int_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_int_ready;
        CData/*1:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_state;
        CData/*1:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_wordsize;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_do_prefetch;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_do_rinst;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_do_rdata;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_do_wdata;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_xfer;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_secondword;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_firstword_reg;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__last_mem_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_firstword;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_firstword_xfer;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__prefetched_high_word;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__clear_prefetched_high_word;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_use_prefetched_high_word;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_busy;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_done;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lui;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_auipc;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_jal;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_jalr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_beq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_bne;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_blt;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_bge;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_bltu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_bgeu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lw;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lbu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_lhu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sb;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sw;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_addi;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_slti;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sltiu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_xori;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_ori;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_andi;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_slli;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_srli;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_srai;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_add;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sub;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sll;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_slt;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sltu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_xor;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_srl;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_sra;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_or;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_and;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_rdcycle;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_rdcycleh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_rdinstr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_rdinstrh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_ecall_ebreak;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_fence;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_getq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_setq;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_retirq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_maskirq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_waitirq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_timer;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__instr_trap;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_rd;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_rs1;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_rs2;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoder_trigger;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoder_trigger_q;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoder_pseudo_trigger_q;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__compressed_instr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_slli_srli_srai;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_sb_sh_sw;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_sll_srl_sra;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_slti_blt_slt;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_sltiu_bltu_sltu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_lbu_lhu_lw;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_alu_reg_imm;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_alu_reg_reg;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_compare;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_rs1;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_rs2;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_rd;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_rs1val_valid;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_rs2val_valid;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_insn_rs1;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_insn_rs2;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_insn_rd;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_next;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__launch_next_insn;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_valid_insn;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_insn_rs1;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_insn_rs2;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_insn_rd;
        CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state;
        CData/*1:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_state;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__set_mem_do_rinst;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__set_mem_do_rdata;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__set_mem_do_wdata;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_store;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_stalu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_branch;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_compr;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_trace;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_is_lu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_is_lh;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_is_lb;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__latched_rd;
        CData/*3:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_timeout_counter;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_timeout;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__do_waitirq;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_out_0;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_out_0_q;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_wait;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_wait_2;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_eq;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_ltu;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_lts;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__clear_prefetched_high_word_q;
        CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpuregs_write;
        CData/*4:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_rs;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ACLK;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ARESETN;
        CData/*2:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_AWPROT;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_AWVALID;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_AWREADY;
        CData/*3:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_WSTRB;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_WVALID;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_WREADY;
        CData/*1:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_BRESP;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_BVALID;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_BREADY;
        CData/*2:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ARPROT;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ARVALID;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ARREADY;
        CData/*1:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_RRESP;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_RVALID;
        CData/*0:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_RREADY;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ACLK;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ARESETN;
        CData/*3:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_AWADDR;
        CData/*2:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_AWPROT;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_AWVALID;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_AWREADY;
        CData/*3:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_WSTRB;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_WVALID;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_WREADY;
        CData/*1:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_BRESP;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_BVALID;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_BREADY;
        CData/*3:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ARADDR;
        CData/*2:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ARPROT;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ARVALID;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_ARREADY;
        CData/*1:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_RRESP;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_RVALID;
        CData/*0:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_RREADY;
        CData/*7:0*/ soc_top__DOT__s1_mac__DOT__w_val;
        CData/*7:0*/ soc_top__DOT__s1_mac__DOT__a_val;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_16bit_buffer;
        SData/*15:0*/ soc_top__DOT__s1_mac__DOT__prod_val;
        IData/*31:0*/ soc_top__DOT__mem_axi_awaddr;
        IData/*31:0*/ soc_top__DOT__mem_axi_wdata;
        IData/*31:0*/ soc_top__DOT__mem_axi_araddr;
        IData/*31:0*/ soc_top__DOT__mem_axi_rdata;
        IData/*31:0*/ soc_top__DOT__s0_axi_rdata;
        IData/*31:0*/ soc_top__DOT__s1_axi_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_axi_awaddr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_axi_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_axi_araddr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_axi_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__pcpi_insn;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__pcpi_rs1;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__pcpi_rs2;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__pcpi_rd;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__irq;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__cpu__DOT__eoi;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__mem_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_awaddr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_araddr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_axi_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__axi_adapter__DOT__mem_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_la_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_insn;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_rs1;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_rs2;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_rd;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__eoi;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_pc;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_next_pc;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_op1;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_op2;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__reg_out;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__next_insn_opcode;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_opcode;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_addr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_wdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_mem_rdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__next_pc;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_mask;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_pending;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__timer;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__i;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_mul_rd;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_div_rd;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__pcpi_int_rd;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_rdata_word;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_rdata_q;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_rdata_latched_noshuffle;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__mem_rdata_latched;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_imm;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__decoded_imm_j;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_insn_imm;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_rs1val;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_rs2val;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_insn_imm;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_insn_opcode;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_insn_imm;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_insn_opcode;
        VlWide<4>/*127:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_ascii_state;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__current_pc;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__next_irq_pending;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_out;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_out_q;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_add_sub;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_shl;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__alu_shr;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpuregs_wrdata;
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpuregs_rs1;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpuregs_rs2;
        IData/*31:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_AWADDR;
        IData/*31:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_WDATA;
        IData/*31:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_ARADDR;
        IData/*31:0*/ soc_top__DOT__s0_ram__DOT__S_AXI_RDATA;
        IData/*31:0*/ soc_top__DOT__s0_ram__DOT__i;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_WDATA;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__S_AXI_RDATA;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__ctrl_reg;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__wgt_reg;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__act_reg;
        IData/*31:0*/ soc_top__DOT__s1_mac__DOT__res_reg;
        IData/*31:0*/ __VactIterCount;
        QData/*35:0*/ soc_top__DOT__cpu__DOT__trace_data;
        QData/*35:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__trace_data;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__count_cycle;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__count_instr;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__new_ascii_instr;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__dbg_ascii_instr;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__q_ascii_instr;
        QData/*63:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cached_ascii_instr;
        VlUnpacked<IData/*31:0*/, 32> soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpuregs;
        VlUnpacked<IData/*31:0*/, 8192> soc_top__DOT__s0_ram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 32768> soc_top__DOT__s0_ram__DOT__mem_8bit;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_COUNTERS = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_COUNTERS64 = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_REGS_16_31 = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_REGS_DUALPORT = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__TWO_STAGE_SHIFT = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__BARREL_SHIFTER = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__TWO_CYCLE_COMPARE = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__TWO_CYCLE_ALU = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__COMPRESSED_ISA = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__CATCH_MISALIGN = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__CATCH_ILLINSN = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_PCPI = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_MUL = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_FAST_MUL = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_DIV = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_IRQ = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_IRQ_QREGS = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_IRQ_TIMER = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__ENABLE_TRACE = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__REGS_INIT_ZERO = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_COUNTERS = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_COUNTERS64 = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_REGS_16_31 = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_REGS_DUALPORT = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__LATCHED_MEM_RDATA = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TWO_STAGE_SHIFT = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__BARREL_SHIFTER = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TWO_CYCLE_COMPARE = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TWO_CYCLE_ALU = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__COMPRESSED_ISA = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__CATCH_MISALIGN = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__CATCH_ILLINSN = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_PCPI = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_MUL = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_FAST_MUL = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_DIV = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_IRQ = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_IRQ_QREGS = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_IRQ_TIMER = 1U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__ENABLE_TRACE = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__REGS_INIT_ZERO = 0U;
    static constexpr CData/*0:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__WITH_PCPI = 0U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_trap = 0x80U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_fetch = 0x40U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_ld_rs1 = 0x20U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_ld_rs2 = 0x10U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_exec = 8U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_shift = 4U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_stmem = 2U;
    static constexpr CData/*7:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__cpu_state_ldmem = 1U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__MASKED_IRQ = 0U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__LATCHED_IRQ = 0xffffffffU;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__PROGADDR_RESET = 0U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__PROGADDR_IRQ = 0x00000010U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__STACKADDR = 0xffffffffU;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__MASKED_IRQ = 0U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__LATCHED_IRQ = 0xffffffffU;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__PROGADDR_RESET = 0U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__PROGADDR_IRQ = 0x00000010U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__STACKADDR = 0xffffffffU;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_timer = 0U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_ebreak = 1U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irq_buserror = 2U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__irqregs_offset = 0x00000020U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__regfile_size = 0x00000020U;
    static constexpr IData/*31:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__regindex_bits = 5U;
    static constexpr IData/*31:0*/ soc_top__DOT__s0_ram__DOT__MEM_SIZE = 0x00008000U;
    static constexpr IData/*31:0*/ soc_top__DOT__s1_mac__DOT__C_S_AXI_DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ soc_top__DOT__s1_mac__DOT__C_S_AXI_ADDR_WIDTH = 4U;
    static constexpr QData/*35:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TRACE_BRANCH = 0x0000000100000000ULL;
    static constexpr QData/*35:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TRACE_ADDR = 0x0000000200000000ULL;
    static constexpr QData/*35:0*/ soc_top__DOT__cpu__DOT__picorv32_core__DOT__TRACE_IRQ = 0x0000000800000000ULL;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
